Repository hzuapps/android-labs-2019, pull requests merged in 2019-03, with the labels that each got.

#10 #1 第一次实验
  students/soft1714080902109/Soft1714080902109Activity.java
Labels: Good

#11 第一次实验
  students/soft1714080902214/AndroidStudio.png
  students/soft1714080902214/Soft1714080902214Activity.java
Labels: Good

#28 创建第一个类
  students/soft1714080902403/Soft1714080902403Activity.java
Labels: Good

#38 #1 提交实验一代码
  students/com1714080901235/Com1714080901235Activity.java
Labels: Good

#45 #1 #YHTION 第一次试验
  students/soft1714080902104/Soft1714080902104Activity.java
Labels: Good

#46 #1 提交实验一代码
  students/soft1714080902102/Soft1714080902102Activity.java
Labels: Good

#64 #1 提交实验一代码
  students/soft1714080902127/Soft1714080902127Activity.java
Labels: Good

#52 #1 提交实验一代码
  students/soft1714080902209/AS运行.png
  students/soft1714080902209/Soft1714080902209Activity.java
Labels: Good

#56 #1 提交实验一代码
  students/com1714080901241/Com1714080901241Activity.java
Labels: Good

#76 #1 提交实验一代码
  students/soft1714080902112/Soft1714080902112Activity.java
Labels: Good

#314 提交实验二代码
  students/soft1707080412124/Soft1707080412124Activity.java
  students/soft1707080412124/app/src/main/AndroidManifest.xml
  students/soft1707080412124/app/src/main/java/edu/hzuapps/androidlabs/soft1707080412124/Soft1707080412124Activity.java
  students/soft1707080412124/app/src/main/res/layout/soft_1707080412124_activity.xml
  students/soft1707080412124/app/src/main/res/values/strings.xml
Labels: Good

#316 提交第二次实验代码
  students/soft1714080902311/app/src/main/AndroidManifest.xml
  students/soft1714080902311/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902311/Soft1714080902311Activity.java
  students/soft1714080902311/app/src/main/res/layout/soft_1714080902311_activity.xml
  students/soft1714080902311/app/src/main/res/values/strings.xml
Labels: Good

#346 #1 提交实验二代码
  students/com1714080901240/app/src/main/AndroidManifest.xml
  students/com1714080901240/app/src/main/java/android/MusicPlayer/Com1714080901240Activity.java
  students/com1714080901240/app/src/main/java/android/MusicPlayer/Com1714080901240Activity_01.java
  students/com1714080901240/app/src/main/java/android/MusicPlayer/Com1714080901240Activity_02.java
  students/com1714080901240/app/src/main/java/android/MusicPlayer/Com1714080901240Service.java
  students/com1714080901240/app/src/main/res/layout/activity_com1714080901240.xml
  students/com1714080901240/app/src/main/res/layout/activity_com1714080901240_01.xml
  students/com1714080901240/app/src/main/res/layout/activity_com1714080901240_02.xml
  students/com1714080901240/app/src/main/res/values/colors.xml
  students/com1714080901240/app/src/main/res/values/strings.xml
  students/com1714080901240/app/src/main/res/values/styles.xml
Labels: Good

#345 soft1714080902214_蚂蚁庄园养鸡大户
  students/soft1714080902214/app/src/main/AndroidManifest.xml
  students/soft1714080902214/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902214/Soft1714080902214Activity.java
  students/soft1714080902214/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902214/Soft1714080902214Activity2.java
  students/soft1714080902214/app/src/main/res/layout/soft_1714080902214_activity.xml
  students/soft1714080902214/app/src/main/res/layout/soft_1714080902214_activity2.xml
  students/soft1714080902214/app/src/main/res/values/strings.xml
Labels: Good

#362 #2 第二次实验
  students/soft1509081602625/app/src/main/AndroidManifest.xml
  students/soft1509081602625/app/src/main/java/Soft1509081602625Activity.java
  students/soft1509081602625/app/src/main/res/activity_soft1509081602625.xml
  students/soft1509081602625/app/src/main/values/strings.xml
Labels: Good

#365 ＃ 2提交实验二代码
  students/com1714080901233/app/src/main/AndroidManifest.xml
  students/com1714080901233/app/src/main/java/edu/hzuapps/androidlabs/com1714080901233/Com1714080901233Activity.java
  students/com1714080901233/app/src/main/res/layout/com_1714080901233_activity.xml
  students/com1714080901233/app/src/main/res/values/strings.xml
Labels: Good

#399 #2提交实验2
  students/soft1714080902132/Soft1714080902132Activity.java
  students/soft1714080902132/实验2/edu/AndroidManifest.xml
  students/soft1714080902132/实验2/edu/hzuapps/androidlabs/soft1714080902132/Soft1714080902132Activity.java
  students/soft1714080902132/实验2/edu/layout/activity_soft1714080902132.xml
  students/soft1714080902132/实验2/edu/values/strings.xml
Labels: Good

#418 #2 提交实验二代码
  students/com1714080901115/app/src/main/AndroidManifest.xml
  students/com1714080901115/app/src/main/java/edu/hzuapps/androidlabs/com1714080901115/Com1714080901115Activity.java
  students/com1714080901115/app/src/main/res/layout/com_1714080901115_activity.xml
  students/com1714080901115/app/src/main/res/values/strings.xml
Labels: Good

#420 #2 提交实验二代码
  students/com1714080901118/app/src/main/AndroidManifest.xml
  students/com1714080901118/app/src/main/java/edu/hzuapps/androidlabs/Com1714080901118/Com1714080901118Activity.java
  students/com1714080901118/app/src/main/res/layout/activity_com1714080901118.xml
  students/com1714080901118/app/src/main/res/values/strings.xml
Labels: Good

#448 update lab2
  students/soft1714080902128/实验1/report1.md
  students/soft1714080902128/实验1/soft1714080902128Activity.java
  students/soft1714080902128/实验1/实验1.png
  students/soft1714080902128/实验2/src/main/AndroidManifest.xml
  students/soft1714080902128/实验2/src/main/java/edu/hzuapps/androidlabs/soft1714080902128/Soft1714080902128Activity.java
  students/soft1714080902128/实验2/src/main/res/layout/activity_main.xml
  students/soft1714080902128/实验2/src/main/res/layout/soft_1714080902128_activity.xml
  students/soft1714080902128/实验2/src/main/res/values/strings.xml
Labels: Copy

#527 第二次实验
  students/soft1714080902234/main/java/edu/hzuapps/androidlabs/soft1714080902234/Soft1714080902234bianqian.java
Labels: Good

#767 #3 实验三
  students/soft1714080902309/实验三/app/src/main/AndroidManifest.xml
  students/soft1714080902309/实验三/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902309/Soft1714080902309Activity.java
  students/soft1714080902309/实验三/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902309/Soft1714080902309Activity2.java
  students/soft1714080902309/实验三/app/src/main/res/drawable/tupian.png
  students/soft1714080902309/实验三/app/src/main/res/layout/soft_1714080902309_activity.xml
  students/soft1714080902309/实验三/app/src/main/res/layout/soft_1714080902309_activity2.xml
  students/soft1714080902309/实验三/app/src/main/res/values/strings.xml
Labels: Good

#812 #3 #309 提交实验三代码
  students/soft1714080902201/app/src/main/AndroidManifest.xml
  students/soft1714080902201/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902201/Soft1714080902201_Activity.java
  students/soft1714080902201/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902201/Soft1714080902201_Activity_2.java
  students/soft1714080902201/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902201/Soft1714080902201_Activity_3.java
  students/soft1714080902201/app/src/main/res/drawable/banner_1.png
  students/soft1714080902201/app/src/main/res/drawable/banner_2.png
  students/soft1714080902201/app/src/main/res/drawable/banner_3.png
  students/soft1714080902201/app/src/main/res/drawable/ic_launcher_background.xml
  students/soft1714080902201/app/src/main/res/layout/activity_soft1714080902201.xml
  students/soft1714080902201/app/src/main/res/layout/activity_soft1714080902201_2.xml
  students/soft1714080902201/app/src/main/res/layout/activity_soft1714080902201_3.xml
  students/soft1714080902201/app/src/main/res/values/strings.xml
Labels: Good

#818 #3 第三次实验
  students/soft1714080902223/app/src/main/AndroidManifest.xml
  students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902223/HomeActivity.java
  students/soft1714080902223/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902223/Soft1714080902223Activity.java
  students/soft1714080902223/app/src/main/res/drawable/btnshape.xml
  students/soft1714080902223/app/src/main/res/drawable/edit_background.jpg
  students/soft1714080902223/app/src/main/res/layout/activity_home.xml
  students/soft1714080902223/app/src/main/res/layout/soft_1714080902223_activity.xml
  students/soft1714080902223/app/src/main/res/values/colors.xml
  students/soft1714080902223/app/src/main/res/values/strings.xml
  students/soft1714080902223/app/src/main/res/values/styles.xml
Labels: Good

#958 #2 #519 第三次实验
  students/soft1714080902307/Test03/app/src/main/AndroidManifest.xml
  students/soft1714080902307/Test03/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Module/AllModuleActivity.java
  students/soft1714080902307/Test03/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Module/EmojiModuleActivity.java
  students/soft1714080902307/Test03/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Module/MediaModuleActivity.java
  students/soft1714080902307/Test03/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Module/ToolModuleActivity.java
  students/soft1714080902307/Test03/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Module/WallpaperModuleActivity.java
  students/soft1714080902307/Test03/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Soft1714080902307Activity.java
  students/soft1714080902307/Test03/app/src/main/res/drawable-v21/background.jpg
  students/soft1714080902307/Test03/app/src/main/res/drawable-v21/ic_menu_media.xml
  students/soft1714080902307/Test03/app/src/main/res/drawable-v21/ic_menu_send.xml
  students/soft1714080902307/Test03/app/src/main/res/drawable-v21/ic_menu_share.xml
  students/soft1714080902307/Test03/app/src/main/res/drawable-v21/ic_menu_tool.xml
  students/soft1714080902307/Test03/app/src/main/res/drawable-v21/ic_menu_wallpaper.xml
  students/soft1714080902307/Test03/app/src/main/res/drawable-v24/all.gif
  students/soft1714080902307/Test03/app/src/main/res/drawable-v24/developing.gif
  students/soft1714080902307/Test03/app/src/main/res/drawable-v24/emoji.gif
  students/soft1714080902307/Test03/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  students/soft1714080902307/Test03/app/src/main/res/drawable-v24/media.gif
  students/soft1714080902307/Test03/app/src/main/res/drawable-v24/tool.gif
  students/soft1714080902307/Test03/app/src/main/res/drawable-v24/wallpaper.gif
  students/soft1714080902307/Test03/app/src/main/res/drawable/ic_launcher_background.xml
  students/soft1714080902307/Test03/app/src/main/res/drawable/ic_menu_emoji.xml
  students/soft1714080902307/Test03/app/src/main/res/drawable/ic_menu_home.xml
  students/soft1714080902307/Test03/app/src/main/res/drawable/ic_search_black_24dp.xml
  students/soft1714080902307/Test03/app/src/main/res/drawable/icon.png
  students/soft1714080902307/Test03/app/src/main/res/drawable/side_nav_bar.xml
  students/soft1714080902307/Test03/app/src/main/res/layout/activity_all_module.xml
  students/soft1714080902307/Test03/app/src/main/res/layout/activity_emoji_module.xml
  students/soft1714080902307/Test03/app/src/main/res/layout/activity_main.xml
  students/soft1714080902307/Test03/app/src/main/res/layout/activity_media_module.xml
  students/soft1714080902307/Test03/app/src/main/res/layout/activity_tool_module.xml
  students/soft1714080902307/Test03/app/src/main/res/layout/activity_wallpaper_module.xml
  students/soft1714080902307/Test03/app/src/main/res/layout/app_bar_main.xml
  students/soft1714080902307/Test03/app/src/main/res/layout/content_main.xml
  students/soft1714080902307/Test03/app/src/main/res/layout/nav_header_main.xml
  students/soft1714080902307/Test03/app/src/main/res/menu/activity_main_drawer.xml
  students/soft1714080902307/Test03/app/src/main/res/menu/main.xml
  students/soft1714080902307/Test03/app/src/main/res/values/colors.xml
  students/soft1714080902307/Test03/app/src/main/res/values/dimens.xml
  students/soft1714080902307/Test03/app/src/main/res/values/drawables.xml
  students/soft1714080902307/Test03/app/src/main/res/values/strings.xml
  students/soft1714080902307/Test03/app/src/main/res/values/styles.xml
Labels: Example, Good

#985 #4 第四次实验
  students/soft1714080902214/第四次实验/AndroidManifest.xml
  students/soft1714080902214/第四次实验/Soft1714080902214Activity3.java
  students/soft1714080902214/第四次实验/Soft1714080902214Activity4.java
  students/soft1714080902214/第四次实验/layout/content_soft17140809022144.xml
  students/soft1714080902214/第四次实验/layout/soft_1714080902214_activity3.xml
  students/soft1714080902214/第四次实验/layout/soft_1714080902214_activity4.xml
  students/soft1714080902214/第四次实验/values/colors.xml
  students/soft1714080902214/第四次实验/values/dimens.xml
  students/soft1714080902214/第四次实验/values/strings.xml
  students/soft1714080902214/第四次实验/values/styles.xml
Labels: Good

#1015 #4 #269 提交实验四代码
  students/com1714080901123/app/src/main/AndroidManifest.xml
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123Activity01.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123Activity02.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123FragmentAmiibo.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123FragmentClothing.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123FragmentCounter.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123FragmentHome.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123FragmentMap.java
  students/com1714080901123/app/src/main/res/drawable/clothing_black.png
  students/com1714080901123/app/src/main/res/drawable/count_black.png
  students/com1714080901123/app/src/main/res/drawable/count_white.png
  students/com1714080901123/app/src/main/res/drawable/logo_amiibo.png
  students/com1714080901123/app/src/main/res/drawable/map_black.png
  students/com1714080901123/app/src/main/res/drawable/map_white.png
  students/com1714080901123/app/src/main/res/drawable/shape_home_button.xml
  students/com1714080901123/app/src/main/res/drawable/squid_black_2.png
  students/com1714080901123/app/src/main/res/drawable/squid_while_2.png
  students/com1714080901123/app/src/main/res/layout/activity_com171408090112301.xml
  students/com1714080901123/app/src/main/res/layout/activity_com171408090112302.xml
  students/com1714080901123/app/src/main/res/layout/activity_main.xml
  students/com1714080901123/app/src/main/res/layout/fragment_com1714080901123_fragment_amiibo.xml
  students/com1714080901123/app/src/main/res/layout/fragment_com1714080901123_fragment_clothing.xml
  students/com1714080901123/app/src/main/res/layout/fragment_com1714080901123_fragment_counter.xml
  students/com1714080901123/app/src/main/res/layout/fragment_com1714080901123_fragment_home.xml
  students/com1714080901123/app/src/main/res/layout/fragment_com1714080901123_fragment_map.xml
  students/com1714080901123/app/src/main/res/menu/navigation.xml
  students/com1714080901123/app/src/main/res/values/strings.xml
  students/com1714080901123/app/src/main/res/values/styles.xml
Labels: Good

#1046 #4 提交实验四
  students/soft1714080902437/app/src/main/AndroidManifest.xml
  students/soft1714080902437/app/src/main/java/edu/hzuapps/soft1714080902437test3/MainActivity.java
  students/soft1714080902437/app/src/main/java/edu/hzuapps/soft1714080902437test3/No2Activity.java
  students/soft1714080902437/app/src/main/java/edu/hzuapps/soft1714080902437test3/No3Activity.java
  students/soft1714080902437/app/src/main/java/edu/hzuapps/soft1714080902437test3/Soft1714080902437Activity.java
  students/soft1714080902437/app/src/main/res/layout/activity_main.xml
  students/soft1714080902437/app/src/main/res/layout/activity_no2.xml
  students/soft1714080902437/app/src/main/res/layout/activity_no3.xml
  students/soft1714080902437/app/src/main/res/layout/activity_soft1714080902437.xml
  students/soft1714080902437/app/src/main/res/mipmap-xxxhdpi/star.jpg
  students/soft1714080902437/app/src/main/res/mipmap-xxxhdpi/thank.jpg
  students/soft1714080902437/app/src/main/res/values/colors.xml
  students/soft1714080902437/app/src/main/res/values/strings.xml
  students/soft1714080902437/app/src/main/res/values/styles.xml
  students/soft1714080902437/src/main/AndroidManifest.xml
  students/soft1714080902437/src/main/res/mipmap-mdpi/star.png
  students/soft1714080902437/src/main/res/values/strings.xml
Labels: Good

#1049 #4 第4次实验
  students/soft1714080902130/实验四/AndroidManifest.xml
  students/soft1714080902130/实验四/java/edu/hzuapps/androidlabs/Soft1714080902130/Soft1714080902130Activity.java
  students/soft1714080902130/实验四/java/edu/hzuapps/androidlabs/Soft1714080902130/Soft1714080902130LoginActivity.java
  students/soft1714080902130/实验四/java/edu/hzuapps/androidlabs/Soft1714080902130/Soft1714080902130SecondActivity.java
  students/soft1714080902130/实验四/res/drawable/bg.xml
  students/soft1714080902130/实验四/res/drawable/first.png
  students/soft1714080902130/实验四/res/drawable/fourth.png
  students/soft1714080902130/实验四/res/drawable/second.png
  students/soft1714080902130/实验四/res/drawable/third.png
  students/soft1714080902130/实验四/res/drawable/timg.jpg
  students/soft1714080902130/实验四/res/layout/activity_soft1714080902130.xml
  students/soft1714080902130/实验四/res/layout/activity_soft1714080902130_login.xml
  students/soft1714080902130/实验四/res/layout/activity_soft1714080902130_second.xml
Labels: Good

#1073 ＃4＃519第四次实验
  students/soft1714080902307/Test04/app/src/main/AndroidManifest.xml
  students/soft1714080902307/Test04/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Function/FirstFunctionActivity.java
  students/soft1714080902307/Test04/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Module/AllModuleActivity.java
  students/soft1714080902307/Test04/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Module/EmojiModuleActivity.java
  students/soft1714080902307/Test04/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Module/MediaModuleActivity.java
  students/soft1714080902307/Test04/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Module/ToolModuleActivity.java
  students/soft1714080902307/Test04/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Module/WallpaperModuleActivity.java
  students/soft1714080902307/Test04/app/src/main/java/com/edu/hzuapps/androidlabs/soft1714080902307/Soft1714080902307Activity.java
  students/soft1714080902307/Test04/app/src/main/res/drawable-v21/background2.png
  students/soft1714080902307/Test04/app/src/main/res/drawable-v21/emoji2.gif
  students/soft1714080902307/Test04/app/src/main/res/drawable-v21/ic_menu_media.xml
  students/soft1714080902307/Test04/app/src/main/res/drawable-v21/ic_menu_send.xml
  students/soft1714080902307/Test04/app/src/main/res/drawable-v21/ic_menu_share.xml
  students/soft1714080902307/Test04/app/src/main/res/drawable-v21/ic_menu_tool.xml
  students/soft1714080902307/Test04/app/src/main/res/drawable-v21/ic_menu_wallpaper.xml
  students/soft1714080902307/Test04/app/src/main/res/drawable-v24/all.gif
  students/soft1714080902307/Test04/app/src/main/res/drawable-v24/developing.gif
  students/soft1714080902307/Test04/app/src/main/res/drawable-v24/emoji.gif
  students/soft1714080902307/Test04/app/src/main/res/drawable-v24/media.gif
  students/soft1714080902307/Test04/app/src/main/res/drawable-v24/tool.gif
  students/soft1714080902307/Test04/app/src/main/res/drawable-v24/wallpaper.gif
  students/soft1714080902307/Test04/app/src/main/res/drawable/background.jpg
  students/soft1714080902307/Test04/app/src/main/res/drawable/ic_menu_emoji.xml
  students/soft1714080902307/Test04/app/src/main/res/drawable/ic_menu_home.xml
  students/soft1714080902307/Test04/app/src/main/res/drawable/ic_settings.xml
  students/soft1714080902307/Test04/app/src/main/res/drawable/icon.png
  students/soft1714080902307/Test04/app/src/main/res/layout/activity_all_module.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/activity_emoji_module.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/activity_first_function.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/activity_main.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/activity_media_module.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/activity_tool_module.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/activity_wallpaper_module.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/app_bar_first_function.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/app_bar_main.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/content_all.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/content_first_function.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/content_main.xml
  students/soft1714080902307/Test04/app/src/main/res/layout/nav_header_main.xml
  students/soft1714080902307/Test04/app/src/main/res/menu/activity_main_drawer.xml
  students/soft1714080902307/Test04/app/src/main/res/menu/main.xml
  students/soft1714080902307/Test04/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  students/soft1714080902307/Test04/app/src/main/res/values/strings.xml
  students/soft1714080902307/Test04/app/src/main/res/values/styles.xml
Labels: Good

#1132 #1 提交实验1代码
  students/soft1714080902342/com/example/asus/myapp/Soft1714080902342Activity.java
Labels: Late

#1162 #5 #533 第五次实验
  students/soft1714080902232/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902232/Soft1714080902232Activity_Success.java
  students/soft1714080902232/app/src/main/res/layout/soft_1714080902232_activity_success.xml
Labels: Good

#1166 #2 第二次提交
  students/soft1714080902342/shiyan2/AndroidManifest.xml
  students/soft1714080902342/shiyan2/Soft1714080902342Activity.java
  students/soft1714080902342/shiyan2/activity_soft1714080902342.xml
  students/soft1714080902342/shiyan2/strings.xml
Labels: Late
