Repository hzuapps/android-labs-2019, pull requests merged in 2019-04, with the labels that each got.

#1197 #2 #279 实验二
  students/soft1714080902325/app/src/main/AndroidManifest.xml
  students/soft1714080902325/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902325/HomeActivity.java
  students/soft1714080902325/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902325/MainActivity.java
  students/soft1714080902325/app/src/main/res/drawable-v24/timg.jpg
  students/soft1714080902325/app/src/main/res/layout/activity_home.xml
  students/soft1714080902325/app/src/main/res/layout/activity_main.xml
  students/soft1714080902325/app/src/main/res/values/strings.xml
Labels: Late

#1187 # 提交实验二代码
  students/soft1714080902338/app/src/main/AndroidManifest.xml
  students/soft1714080902338/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902338/soft1714080902338/MainActivity.java
  students/soft1714080902338/app/src/main/res/layout/activity_main.xml
  students/soft1714080902338/app/src/main/res/values/strings.xml
Labels: Late

#1185 #5 #259 第五次实验
  students/soft1714080902210/实验五/Soft1714080902210Activity_New.java
  students/soft1714080902210/实验五/activity_soft1714080902210__new.xml
  students/soft1714080902210/实验五/微信截图_20190331120115.jpg
  students/soft1714080902210/实验五/微信截图_20190331120147.jpg
Labels: Good

#1196 #5 第五次实验
  students/soft1714080902214/第五次实验/Soft1714080902214Activity3.java
  students/soft1714080902214/第五次实验/Soft1714080902214Activity4.java
  students/soft1714080902214/第五次实验/soft_1714080902214_activity3.xml
  students/soft1714080902214/第五次实验/soft_1714080902214_activity4.xml
Labels: Good

#1216 #2 实验二
  students/soft1714080902337/实验2/AndroidManifest.xml
  students/soft1714080902337/实验2/Soft1714080902337Activity.java
  students/soft1714080902337/实验2/soft_1714080902337_activity.xml
  students/soft1714080902337/实验2/strings.xml
Labels: Late

#1210 #5 #275 第五次实验
  students/soft1714080902336/shiyan5/AddActivity.java
  students/soft1714080902336/shiyan5/Soft1714080902336Activity.java
  students/soft1714080902336/shiyan5/activity_add.xml
  students/soft1714080902336/shiyan5/activity_soft1714080902336.xml
Labels: Good

#1211 #5 #290 提交实验五代码文件
  students/soft1714080902339/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902339/SecondActivity.java
  students/soft1714080902339/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902339/WriteActivity.java
  students/soft1714080902339/app/src/main/res/layout/activity_write.xml
  students/soft1714080902339/app/src/main/res/layout/second_activity.xml
Labels: Good

#1217 #5 #muxuny第五次实验
  students/soft1714080902226/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902226activity/Soft1714080902226Activity2.java
  students/soft1714080902226/app/src/main/res/layout/activity2_soft17140809022262.xml
Labels: Example, Good

#1222 #5 #llinzhe 提交第五次实验
  students/soft1714080902231/MyApplication5/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902231/Course.java
  students/soft1714080902231/MyApplication5/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902231/DatabaseHelper.java
  students/soft1714080902231/MyApplication5/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902231/MainActivity.java
  students/soft1714080902231/MyApplication5/app/src/main/res/drawable/bg.jpg
  students/soft1714080902231/MyApplication5/app/src/main/res/layout/activity_main.xml
Labels: Good

#1228 #5 #342 提交实验五
  students/soft1714080902205/app/src/main/AndroidManifest.xml
  students/soft1714080902205/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902205/NewActivity.java
  students/soft1714080902205/app/src/main/res/layout/activity_new.xml
Labels: Good

#1251 #5 #339 Exp5_文件存储_HRMS
  students/soft1714080902209/HR管理系统/app/src/main/AndroidManifest.xml
  students/soft1714080902209/HR管理系统/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902209_AddInfo.java
  students/soft1714080902209/HR管理系统/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902209_Login.java
  students/soft1714080902209/HR管理系统/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902209_Reg.java
  students/soft1714080902209/HR管理系统/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902209_UPSQL.java
  students/soft1714080902209/HR管理系统/app/src/main/res/layout/soft1714080902209_addinfo.xml
  students/soft1714080902209/HR管理系统/app/src/main/res/layout/soft1714080902209_login.xml
  students/soft1714080902209/HR管理系统/app/src/main/res/values/strings.xml
Labels: Example, Good

#1301 #6 #382 提交实验六代码
  students/soft1714080902127/shiyan_6/json/get_data.json
  students/soft1714080902127/shiyan_6/main/AndroidManifest.xml
  students/soft1714080902127/shiyan_6/main/java/edu/hzuapps/androidlabs/soft1714080902127/App.java
  students/soft1714080902127/shiyan_6/main/java/edu/hzuapps/androidlabs/soft1714080902127/Soft1714080902127MainActivity.java
Labels: Example, Good

#1309 #5 #269 提交实验五代码
  students/com1714080901123/app/src/main/AndroidManifest.xml
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123ActivityAmiibo.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123ActivityMain.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123ActivitySelectAbility.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123ActivitySelectWeapon.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123FragmentAmiibo.java
  students/com1714080901123/app/src/main/java/edu/hzuapps/androidlabs/com1714080901123/Com1714080901123FragmentCounter.java
  students/com1714080901123/app/src/main/res/layout/activity_com1714080901123_amiibo.xml
  students/com1714080901123/app/src/main/res/layout/activity_com1714080901123_select_ability.xml
  students/com1714080901123/app/src/main/res/layout/activity_com1714080901123_select_weapon.xml
  students/com1714080901123/app/src/main/res/layout/activity_main.xml
  students/com1714080901123/app/src/main/res/layout/content_com1714080901123_activity_amiibo.xml
  students/com1714080901123/app/src/main/res/layout/content_com1714080901123_activity_select_ability.xml
  students/com1714080901123/app/src/main/res/layout/content_com1714080901123_activity_select_weapon.xml
  students/com1714080901123/app/src/main/res/layout/fragment_com1714080901123_fragment_amiibo.xml
  students/com1714080901123/app/src/main/res/layout/fragment_com1714080901123_fragment_counter.xml
  students/com1714080901123/app/src/main/res/values/strings.xml
  students/com1714080901123/app/src/main/res/values/styles.xml
Labels: Example, Good

#1355 #2 #1333 提交实验2代码
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com17140809011MainActivity.java
  students/com171408901141/app/src/main/res/layout/activity_main.xml
  students/com171408901141/app/src/main/res/menu/navigation.xml
  students/com171408901141/app/src/main/res/values/strings.xml
Labels: Late

#1368 #3 提交实验三代码
  students/soft1714080902337/实验3/AndroidManifest.xml
  students/soft1714080902337/实验3/Soft1714080902337Activity.java
  students/soft1714080902337/实验3/Soft1714080902337Activity2.java
  students/soft1714080902337/实验3/colors.xml
  students/soft1714080902337/实验3/hua.jpg
  students/soft1714080902337/实验3/ic_launcher_background.xml
  students/soft1714080902337/实验3/soft_1714080902337_activity.xml
  students/soft1714080902337/实验3/soft_1714080902337_activity2.xml
  students/soft1714080902337/实验3/strings.xml
  students/soft1714080902337/实验3/styles.xml
Labels: Late

#1341 #6 #309 #提交实验六代码
  students/soft1714080902201/app/src/main/AndroidManifest.xml
  students/soft1714080902201/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902201/Soft1714080902201_Activity.java
  students/soft1714080902201/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902201/Soft1714080902201_Activity_Recommendation.java
  students/soft1714080902201/app/src/main/res/assets/book
  students/soft1714080902201/app/src/main/res/drawable/profile_photo.jpg
  students/soft1714080902201/app/src/main/res/drawable/side_nav_bar.xml
  students/soft1714080902201/app/src/main/res/layout/activity_soft1714080902201_recommendation.xml
  students/soft1714080902201/app/src/main/res/layout/activity_soft1714080902201_recommendation_item.xml
Labels: Example, Good

#1380 #4 #1178 第四次实验
  students/soft1714080902340/drawable/ic_launcher_background.xml
  students/soft1714080902340/drawable/themonkeyking3.jpg
  students/soft1714080902340/layout/first_layout.xml
  students/soft1714080902340/layout/second_layout.xml
  students/soft1714080902340/menu/main.xml
  students/soft1714080902340/myapplication/FirstActivity.java
  students/soft1714080902340/myapplication/SecondActivity.java
  students/soft1714080902340/pomodoros_layout.xml
  students/soft1714080902340/values/colors.xml
  students/soft1714080902340/values/strings.xml
  students/soft1714080902340/values/styles.xml
Labels: Late

#1369 #6 #449 提交第六次实验
  students/soft1714080902430/app/src/main/AndroidManifest.xml
  students/soft1714080902430/app/src/main/java/com/hzu/zgg/InternetActivity.java
  students/soft1714080902430/app/src/main/res/layout/activity_internet.xml
  students/soft1714080902430/girl.json
Labels: Good

#1400 #3 #1333 提交实验3代码
  students/com171408901141/app/src/main/AndroidManifest.xml
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141ActivityCollector.java
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141BaseActivity.java
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141DialogActivity.java
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141MainActivity.java
  students/com171408901141/app/src/main/res/layout/activity_dialog.xml
  students/com171408901141/app/src/main/res/layout/activity_main.xml
  students/com171408901141/app/src/main/res/menu/navigation.xml
  students/com171408901141/app/src/main/res/values/strings.xml
  students/com171408901141/app/src/main/res/values/styles.xml
Labels: Late

#1330 #6 #533 第六次实验
  students/soft1714080902232/app/src/main/AndroidManifest.xml
  students/soft1714080902232/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902232/Soft1714080902232Activity_MyImageView.java
  students/soft1714080902232/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902232/Soft1714080902232Activity_Web.java
  students/soft1714080902232/app/src/main/res/layout/soft_1714080902232_activity_web.xml
Labels: Example, Good

#1423 #3 #482 补交实验3代码
  students/com1714080901106/app/src/main/java/edu/hzuapps/androidlabs/com1714080901106/Activity_Achievement.java
  students/com1714080901106/app/src/main/java/edu/hzuapps/androidlabs/com1714080901106/Activity_Collection.java
  students/com1714080901106/app/src/main/res/layout/fragment_achievement.xml
  students/com1714080901106/app/src/main/res/layout/fragment_checkpoint.xml
  students/com1714080901106/app/src/main/res/layout/fragment_collection.xml
Labels: Late

#1399 #6 #1286 实验六代码
  students/Soft1714080902239/app/src/main/AndroidManifest.xml
  students/Soft1714080902239/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902239/HttpThread.java
  students/Soft1714080902239/app/src/main/java/edu/hzuapps/androidlabs/Soft1714080902239/MainActivity.java
  students/Soft1714080902239/app/src/main/res/layout/soft_1714080902239_activity/activity_main.xml
Labels: Example, Good

#1431 #6 #1003 提交实验6代码 修改背景图片
  students/com1714080901131/app/src/main/AndroidManifest.xml
  students/com1714080901131/app/src/main/java/edu/hzuapps/androidlabs/com1714080901131/Com1714080901131Activity.java
  students/com1714080901131/app/src/main/res/layout/com_1714080901131_activity.xml
  students/com1714080901131/app/src/main/res/values/strings.xml
Labels: Example, Good

#1439 #6 #302 提交实验六代码 下载图片
  students/soft1714080902311/实验六/SecondActivity.java
  students/soft1714080902311/实验六/activity_second.xml
Labels: Example, Good

#1455 #6 提交实验6代码
  students/soft1714080902309/实验6/app/src/main/AndroidManifest.xml
  students/soft1714080902309/实验6/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902309/Soft1714080902309Activity.java
  students/soft1714080902309/实验6/app/src/main/res/layout/soft_1714080902309_activity.xml
  students/soft1714080902309/实验6/app/src/main/res/values/strings.xml
  students/soft1714080902309/实验六/app/src/main/res/drawable/tupian.png
Labels: Example, Good

#1477 #4 #1214 #第四次实验
  students/soft1714080902422/app/src/main/AndroidManifest.xml
  students/soft1714080902422/app/src/main/java/com/example/administrator/soft1714080902422/FileStorage.java
  students/soft1714080902422/app/src/main/java/com/example/administrator/soft1714080902422/NewActivity.java
  students/soft1714080902422/app/src/main/java/com/example/administrator/soft1714080902422/Soft1714080902422.java
  students/soft1714080902422/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  students/soft1714080902422/app/src/main/res/drawable/background.jpg
  students/soft1714080902422/app/src/main/res/drawable/ic_launcher_background.xml
  students/soft1714080902422/app/src/main/res/layout/activity_new.xml
  students/soft1714080902422/app/src/main/res/layout/activity_soft1714080902422.xml
  students/soft1714080902422/app/src/main/res/layout/content_my.xml
  students/soft1714080902422/app/src/main/res/values/colors.xml
  students/soft1714080902422/app/src/main/res/values/dimens.xml
  students/soft1714080902422/app/src/main/res/values/strings.xml
  students/soft1714080902422/app/src/main/res/values/styles.xml
Labels: Late

#1475 #268 第六次试验
  students/soft1714080902113/app/src/main/AndroidManifest.xml
  students/soft1714080902113/app/src/main/java/com/example/soft1714080902113myexpress/MainActivity.java
  students/soft1714080902113/app/src/main/java/com/example/soft1714080902113myexpress/expresses.java
  students/soft1714080902113/app/src/main/res/layout/activity_main.xml
  students/soft1714080902113/myData.json
Labels: Example, Good

#1478 #6 实验六
  students/soft1714080902105/app/libs/dom4j-1.6.1.jar
  students/soft1714080902105/app/src/main/java/example/senior1104/Soft1714080902105Activity.java
  students/soft1714080902105/app/src/main/java/example/senior1104/student/Student.java
  students/soft1714080902105/app/src/main/java/example/senior1104/student/StudentAddActivity.java
  students/soft1714080902105/app/src/main/java/example/senior1104/student/StudentManager.java
  students/soft1714080902105/app/src/main/res/drawable/ic_titlebar_back.png
  students/soft1714080902105/app/src/main/res/drawable/ic_titlebar_cancel.png
  students/soft1714080902105/app/src/main/res/drawable/ic_titlebar_menu.png
  students/soft1714080902105/app/src/main/res/drawable/ic_titlebar_new.png
  students/soft1714080902105/app/src/main/res/layout/activity_student_add.xml
  students/soft1714080902105/app/src/main/res/layout/list_item_student.xml
  students/soft1714080902105/app/src/main/res/layout/titlebar_dialog.xml
  students/soft1714080902105/app/src/main/res/layout/titlebar_main.xml
Labels: Example, Good

#1487 实验三
  students/soft1714080902301/实验3/app/src/main/java/com/example/myapplication/Main2Activity.java
  students/soft1714080902301/实验3/app/src/main/java/com/example/myapplication/MainActivity.java
  students/soft1714080902301/实验3/app/src/main/res/layout/activity_main.xml
  students/soft1714080902301/实验3/app/src/main/res/layout/activity_main2.xml
Labels: Late

#1484 #6 第六次实验 解析XML
  students/soft1714080902214/userinfo.xml
  students/soft1714080902214/第六次实验/Soft1714080902214Activity5.java
  students/soft1714080902214/第六次实验/User.java
  students/soft1714080902214/第六次实验/UserService.java
Labels: Example, Good

#1496 #6 第6次实验 HttpURLConnection下载图片
  students/soft1714080902433/six/app/src/main/AndroidManifest.xml
  students/soft1714080902433/six/app/src/main/java/com/example/lenovo/soft1714080902433/Activity02.java
  students/soft1714080902433/six/app/src/main/java/com/example/lenovo/soft1714080902433/Activity03.java
  students/soft1714080902433/six/app/src/main/java/com/example/lenovo/soft1714080902433/MainActivity.java
  students/soft1714080902433/six/app/src/main/res/layout/activity02.xml
  students/soft1714080902433/six/app/src/main/res/layout/activity03.xml
  students/soft1714080902433/six/app/src/main/res/layout/activity_main.xml
  students/soft1714080902433/six/app/src/main/res/values/colors.xml
  students/soft1714080902433/six/app/src/main/res/values/strings.xml
  students/soft1714080902433/six/app/src/main/res/values/styles.xml
Labels: Example, Good

#1498 #6 提交实验六代码 OkHttpClient访问并解析JSON
  students/Soft1714080902106/实验6/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902106/Soft1714080902106Activity1.java
  students/Soft1714080902106/实验6/app/src/main/res/layout/soft_1714080902106_activity1.xml
  students/Soft1714080902106/实验6/数据文件/games.json
Labels: Example, Good

#1502 #6 #520 第六次实验 HttpURLConnection下载图片
  students/soft1714080902436/app/src/main/AndroidManifest.xml
  students/soft1714080902436/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902436/Soft1714080902436Activity.java
  students/soft1714080902436/app/src/main/res/layout/soft_1714080902436_activity.xml
  students/soft1714080902436/app/src/main/res/values/strings.xml
Labels: Example, Good

#1517 #261 第五次实验
  students/soft1714080902228/Main2Activity.java
  students/soft1714080902228/MainActivity.java
  students/soft1714080902228/activity_main.xml
  students/soft1714080902228/activity_main2.xml
Labels: Late

#1505 提交实验七代码 传感器的使用
  students/soft1714080902208/实验七/AndroidManifest.xml
  students/soft1714080902208/实验七/java/MainActivity.java
  students/soft1714080902208/实验七/layout/activity_main.xml
  students/soft1714080902208/实验七/layout/content_main.xml
Labels: Example, Good

#1522 #5 #473 第5次实验
  students/com1714080901238/app/src/main/java/edu/hzuapps/androidlabs/Com1714080901238Activity02.java
  students/com1714080901238/app/src/main/res/drawable/ic_launcher_background.xml
  students/com1714080901238/app/src/main/res/layout/com_1714080901238_activity02.xml
Labels: Late

#1525 #4 #1052 更正实验四代码
  soft1714080902318/app/src/main/AndroidManifest.xml
  soft1714080902318/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902318/FourthActivity.java
  soft1714080902318/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902318/SecondActivity.java
  soft1714080902318/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902318/Soft1714080902318MainActivity.java
  soft1714080902318/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902318/ThirdActivity.java
  soft1714080902318/app/src/main/res/layout/activity_fourth.xml
  soft1714080902318/app/src/main/res/layout/activity_second.xml
  soft1714080902318/app/src/main/res/layout/activity_soft1714080902318_main.xml
  soft1714080902318/app/src/main/res/layout/activity_third.xml
Labels: Late

#1548 #3 #274 第三次实验
  students/soft1707080714328/app/src/main/java/ezu/hzuapps/androidlabs/soft1707080714328/Soft1707080714328Activity.java
  students/soft1707080714328/app/src/main/java/ezu/hzuapps/androidlabs/soft1707080714328/Soft1707080714328Activity_First.java
  students/soft1707080714328/app/src/main/res/drawable/skip.png
  students/soft1707080714328/app/src/main/res/layout/soft_1707080714328_activity__first.xml
Labels: Late

#1533 #5 #1178 实验5 内部存储
  students/soft1714080902340/layout/three_activity.xml
  students/soft1714080902340/myapplication/FirstActivity.java
  students/soft1714080902340/myapplication/ThreeActivity.java
Labels: Late

#1560 #282 实验四、五
  students/soft1714080902322/app/src/main/AndroidManifest.xml
  students/soft1714080902322/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902322/FilesaveActivity.java
  students/soft1714080902322/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902322/FirstActivity.java
  students/soft1714080902322/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902322/SecondActivity.java
  students/soft1714080902322/app/src/main/res/drawable/classroom.jpg
  students/soft1714080902322/app/src/main/res/layout/activity_filesave.xml
  students/soft1714080902322/app/src/main/res/layout/activity_main.xml
  students/soft1714080902322/app/src/main/res/layout/activity_second.xml
  students/soft1714080902322/app/src/main/res/values/strings.xml
  students/soft1714080902322/保存数据.jpg
  students/soft1714080902322/教学楼.jpg
  students/soft1714080902322/读取数据.jpg
  students/soft1714080902322/首页.jpg
Labels: Late

#1559 #7 #533 第七次实验 提示手机屏幕旋转
  students/soft1714080902232/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902232/Soft1714080902232Activity_Before.java
  students/soft1714080902232/app/src/main/res/drawable/ic_launcher_photo03.jpg
  students/soft1714080902232/app/src/main/res/layout/soft_1714080902232_activity_before2.xml
Labels: Example, Good

#1581 #7 #372 提交实验7代码 使用BroadReceiver监听网络状态
  students/soft1714080902121/app/src/main/RateList.json
  students/soft1714080902121/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902121/exratecalculator/Soft1714080902121MainActivity.java
  students/soft1714080902121/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902121/exratecalculator/Soft1714080902121RateListActivity.java
  students/soft1714080902121/app/src/main/res/values/strings.xml
Labels: Example, Good

#1584 #5 #492 第五次实验代码
  students/soft1714080902129/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902129/electricitypaymentsystem/Soft1714080902129Activity.java
  students/soft1714080902129/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902129/electricitypaymentsystem/Soft1714080902129Activity2.java
  students/soft1714080902129/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902129/electricitypaymentsystem/Soft1714080902129Activity3.java
  students/soft1714080902129/app/src/main/res/layout/activity_soft1714080902129.xml
  students/soft1714080902129/app/src/main/res/layout/activity_soft17140809021292.xml
  students/soft1714080902129/app/src/main/res/layout/activity_soft17140809021293.xml
Labels: Late

#1586 #5 #482 补交实验5代码
  students/com1714080901106/app/src/main/java/edu/hzuapps/androidlabs/com1714080901106/Activity_Checkpoint.java
  students/com1714080901106/app/src/main/java/edu/hzuapps/androidlabs/com1714080901106/Activity_Introduction.java
  students/com1714080901106/app/src/main/java/edu/hzuapps/androidlabs/com1714080901106/Activity_Login.java
  students/com1714080901106/app/src/main/java/edu/hzuapps/androidlabs/com1714080901106/Com1714080901106Activity01.java
  students/com1714080901106/app/src/main/res/layout/fragment_checkpoint.xml
  students/com1714080901106/app/src/main/res/layout/fragment_introduction.xml
  students/com1714080901106/app/src/main/res/layout/login.xml
  students/com1714080901106/app/src/main/res/layout/main_activity_01.xml
  students/com1714080901106/app/src/main/res/menu/navigation.xml
  students/com1714080901106/app/src/main/res/values/strings.xml
Labels: Late

#1583 #7 #249 获取用户位置信息方便得知当地时区时间
  students/soft1714080902216/edu/hzuapps/androidlabs/soft1714080902216/Soft1714080902216LocationActivity.java
  students/soft1714080902216/edu/hzuapps/androidlabs/soft1714080902216/Soft1714080902216MainActivity.java
  students/soft1714080902216/layout/activity_main.xml
  students/soft1714080902216/layout/activity_soft1714080902216_location.xml
Labels: Example, Good

#1585 #7 #332 实验七设备编程 实现摇一摇功能
  students/com1714080901237/app/src/main/assets/shujuxml.xml
  students/com1714080901237/app/src/main/java/com/example/eduhuzappfuyouapp/Com1714080901237Activity03.java
  students/com1714080901237/app/src/main/java/com/example/eduhuzappfuyouapp/NetworkFileDownloader.java
  students/com1714080901237/app/src/main/layout/activity03_com1714080901237.xml
Labels: Example, Good

#1589 实验四
  students/soft1714080902301/实验4/main/java/com/example/myapplication/Main2Activity.java
  students/soft1714080902301/实验4/main/java/com/example/myapplication/MainActivity.java
  students/soft1714080902301/实验4/main/res/layout/activity_main.xml
  students/soft1714080902301/实验4/main/res/layout/activity_main2.xml
Labels: Late

#1609 #5 #1333 提交实验5代码
  students/com171408901141/app/src/main/AndroidManifest.xml
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141ActivityCollector.java
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141BaseActivity.java
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141DialogActivity.java
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141FragmentStudy.java
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com1714080901141MainActivity.java
  students/com171408901141/app/src/main/java/edu/hzuapps/androidlabs/com1714080901141/Com17140809011MainActivity.java
  students/com171408901141/app/src/main/res/layout/activity_dialog.xml
  students/com171408901141/app/src/main/res/layout/activity_main.xml
  students/com171408901141/app/src/main/res/layout/fregment_study.xml
  students/com171408901141/app/src/main/res/menu/navigation.xml
  students/com171408901141/app/src/main/res/values/strings.xml
  students/com171408901141/app/src/main/res/values/styles.xml
Labels: Late

#1624 #5 #1052 提交实验五代码+补交实验四代码到自己的库内
  students/soft1714080902318/app/src/main/AndroidManifest.xml
  students/soft1714080902318/app/src/main/java/com/example/myapplication/myapplication02/FourthActivity.java
  students/soft1714080902318/app/src/main/java/com/example/myapplication/myapplication02/SecondActivity.java
  students/soft1714080902318/app/src/main/java/com/example/myapplication/myapplication02/Soft1714080902318MainActivity.java
  students/soft1714080902318/app/src/main/java/com/example/myapplication/myapplication02/ThirdActivity.java
  students/soft1714080902318/app/src/main/res/layout/activity_fourth.xml
  students/soft1714080902318/app/src/main/res/layout/activity_second.xml
  students/soft1714080902318/app/src/main/res/layout/activity_soft1714080902318_main.xml
  students/soft1714080902318/app/src/main/res/layout/activity_third.xml
Labels: Late

#1627 #5 #258 提交实验五--代码
  students/soft1714080902207/消费管家/app/src/main/AndroidManifest.xml
  students/soft1714080902207/消费管家/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902207/MyDataBase.java
  students/soft1714080902207/消费管家/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902207/Soft_1714080902207_MainActivity.java
  students/soft1714080902207/消费管家/app/src/main/res/layout/soft_1714080902207_activity_main.xml
  students/soft1714080902207/消费管家/app/src/main/res/layout/soft_1714080902207_activity_second.xml
  students/soft1714080902207/消费管家/app/src/main/res/layout/soft_1714080902207_content_activity.xml
  students/soft1714080902207/消费管家/app/src/main/res/values/strings.xml
  students/soft1714080902207/消费管家/演示截图/主界面-保存.jpg
  students/soft1714080902207/消费管家/演示截图/主界面-查看.jpg
  students/soft1714080902207/消费管家/演示截图/主界面.jpg
Labels: Late

#1634 #7 #1135 提交实验七代码
  students/soft1714080902116/MyApplicationfour/app/src/main/AndroidManifest.xml
  students/soft1714080902116/MyApplicationfour/app/src/main/java/edu/huzapps/androidlabs/soft1714080902116/Main3Activity.java
  students/soft1714080902116/MyApplicationfour/app/src/main/res/layout/activity_main2_soft1714080902116.xml
  students/soft1714080902116/MyApplicationfour/app/src/main/res/layout/activity_main3.xml
  students/soft1714080902116/MyApplicationfour/app/src/main/res/xml/file_paths.xml
Labels: Example, Good

#1675 #5 实验五代码
  students/com1714080901120/app/src/main/AndroidManifest.xml
  students/com1714080901120/app/src/main/java/edu/hzuapps/androidlabs/com1714080901120/Com1714080901120Activity.java
  students/com1714080901120/app/src/main/java/edu/hzuapps/androidlabs/com1714080901120/Com1714080901120Activity2.java
  students/com1714080901120/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  students/com1714080901120/app/src/main/res/drawable-v24/生日.jpg
  students/com1714080901120/app/src/main/res/layout/com_1714080901120_activity.xml
  students/com1714080901120/app/src/main/res/layout/com_1714080901120_activity2.xml
  students/com1714080901120/app/src/main/res/values/strings.xml
Labels: Late

#1678 #5 #277 提交实验5
  students/soft1714080902319/shiyan5/AndroidManifest.xml
  students/soft1714080902319/shiyan5/MainActivity.java
  students/soft1714080902319/shiyan5/soft1714080902319.xml
Labels: Late

#1682 #6 实验6
  students/soft1714080902102/app/src/main/AndroidManifest.xml
  students/soft1714080902102/app/src/main/java/edu/hzuapps/androidlabs/soft1714080902102/NetworkActivity.java
  students/soft1714080902102/app/src/main/res/layout/activity_network.xml
Labels: Late

#1689 #4 #219 实验四代码
  students/com1709081602330/app/src/main/AndroidManifest.xml
  students/com1709081602330/app/src/main/java/edu/hzuapps/androidlabs/com1709081602330/Com1709081602330Activity.java
  students/com1709081602330/app/src/main/java/edu/hzuapps/androidlabs/com1709081602330/Com1709081602330Activity2.java
  students/com1709081602330/app/src/main/java/edu/hzuapps/androidlabs/com1709081602330/MainActivity.java
  students/com1709081602330/app/src/main/java/edu/hzuapps/androidlabs/com1709081602330/Sports_sort.java
  students/com1709081602330/app/src/main/res/drawable/go.png
  students/com1709081602330/app/src/main/res/drawable/ic_launcher_background.xml
  students/com1709081602330/app/src/main/res/drawable/img_1.png
  students/com1709081602330/app/src/main/res/drawable/spurs.png
  students/com1709081602330/app/src/main/res/layout/activity_main.xml
  students/com1709081602330/app/src/main/res/layout/activity_sports_sort.xml
  students/com1709081602330/app/src/main/res/layout/com_1709081602330_activity.xml
  students/com1709081602330/app/src/main/res/layout/com_1709081602330_activity2.xml
  students/com1709081602330/app/src/main/res/values/colors.xml
  students/com1709081602330/app/src/main/res/values/strings.xml
  students/com1709081602330/app/src/main/res/values/styles.xml
Labels: Late

#1711 #1 提交第一次实验代码
  students/soft1714080902140/AndroidManifest.xml
  students/soft1714080902140/java/edu/hzuapps/androidlabs/soft1714080902140/English.java
  students/soft1714080902140/java/edu/hzuapps/androidlabs/soft1714080902140/Soft1714080902140Activity.java
  students/soft1714080902140/res/layout/activity_english.xml
  students/soft1714080902140/res/layout/activity_soft1714080902140.xml
  students/soft1714080902140/res/values/colors.xml
  students/soft1714080902140/res/values/strings.xml
  students/soft1714080902140/res/values/styles.xml
Labels: Late
